### ISSUE TITLE
About Multi-Stage Multi-Task Learning

### ISSUE THREAD

**Issue by hongyuntw** [srijankr/petgen#1]
Hi author! 
Thank for your interesting great work.
But I am confuse about Multi-Stage Multi-Task Learning mentioned in paper
![image](https://user-images.githubusercontent.com/39511654/180645476-157f423a-b69a-4ed0-9f9b-59b528df0805.png)
According to this picture in paper
I would like to know when we do multi-stage multi-task learning
For each task training, should we train the task until convergence and then move on to the next task, or do we just need to train some epochs (steps) and then we can switch to the next task?

Thank you.

**Comment by binghe2727** [comment]
Hi, thanks for your interest. Your second answer is what we did.
